# Generated by Django 5.2 on 2025-04-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_price_order_total_price_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
