# Generated by Django 5.2 on 2025-09-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Home', 'Home'), ('Beauty', 'Beauty'), ('Sports', 'Sports'), ('Toys', 'Toys'), ('Automotive', 'Automotive'), ('Health', 'Health'), ('Grocery', 'Grocery'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50),
        ),
    ]
