# Generated by Django 5.2 on 2025-05-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
