# Generated by Django 5.2 on 2025-05-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customerprofile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='logo',
            new_name='logo_url',
        ),
    ]
