# Generated by Django 5.2 on 2025-06-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_logo_sellerprofile_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_type',
            field=models.CharField(choices=[('private', 'Private'), ('business', 'Business')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
