# Generated by Django 5.2 on 2025-06-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_address_remove_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
